### ISSUE TITLE
Image for README

### ISSUE THREAD

**Issue by rajat2797** [pchhiller/CodeChefQuestionsDownload#12]
![demo](https://user-images.githubusercontent.com/17715883/32132278-bc4c102c-bbde-11e7-8edd-f83f3476d299.png)

**Comment by pchhiller** [comment]
Resolved?

**Comment by rajat2797** [comment]
Bas image k liye banaya tha ab close kar de chahe toh

**Comment by pchhiller** [comment]
Issue fixed by Rajat .
